version: 2
jobs:
  build:
    build:
    parallelism: 1
    machine:
       image: ubuntu-2004:202101-01
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      
